IF (NOT EXISTS (
SELECT *  FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' 
AND  TABLE_NAME = 'KeyValueStore'))
BEGIN
	CREATE TABLE [dbo].[KeyValueStore]
	(
		[Id] NVARCHAR(50) NOT NULL, 
		[Value] NVARCHAR(MAX) NOT NULL, 
		[Type] NVARCHAR(150) NOT NULL,
		[RowId] ROWVERSION NOT NULL,     
		[LastUpdated] DATETIME2 NOT NULL,
		CONSTRAINT [PK_KeyValueStore] PRIMARY KEY CLUSTERED 
		(
			[Id] ASC,
			[Type] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]		
END;
TRUNCATE TABLE [dbo].[KeyValueStore];

IF (NOT EXISTS (
SELECT *  FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' 
AND  TABLE_NAME = 'Relation'))
BEGIN
	CREATE TABLE [dbo].[Relation]
	(
		[Parent] NVARCHAR(50) NOT NULL, 
		[ParentType] NVARCHAR(150) NOT NULL,
		[Child] NVARCHAR(50) NOT NULL,
		[ChildType] NVARCHAR(150) NOT NULL,
		[RowId] ROWVERSION NOT NULL,     
		[LastUpdated] DATETIME2 NOT NULL,
		CONSTRAINT [PK_Relation] PRIMARY KEY CLUSTERED 
		(
			[Parent] ASC,
			[ParentType] ASC,
			[Child] ASC,
			[ChildType] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]			
END;
TRUNCATE TABLE [dbo].[Relation];